### ISSUE TITLE
Consider the type of view-model

### ISSUE THREAD

**Issue by sw1nn** [MastodonC/venue#5]
See https://github.com/cemerick/clojure-type-selection-flowchart/

At first glance, view-model should be deftype, but suspect defrecord might  be useful

**Comment by acron0** [comment]
Could you provide more information as to why you think `reify` is not appropriate? Or why a named type would be more appropriate?

**Comment by acron0** [comment]
So we chatted about this and agree that this is grey territory in terms of what's "the right way". For now, it'll do, but if a better way becomes obvious then it should definitely be investigated,
